# Generated by Django 4.1.1 on 2022-09-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(choices=[('A1', 'A1')], max_length=2)),
                ('B', models.CharField(choices=[('100', '100')], max_length=3)),
                ('C', models.CharField(choices=[('S', 'S'), ('D', 'D'), ('M', 'M')], max_length=2)),
                ('D', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=2)),
                ('E', models.CharField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2)),
                ('F', models.CharField(choices=[('U', 'U'), ('D', 'D')], max_length=2)),
                ('G', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=2)),
                ('H', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=2)),
                ('I', models.CharField(choices=[('12', 'DC Fail Window N')], max_length=20)),
                ('J', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=2)),
                ('K', models.CharField(choices=[('11', 'AC Fail Window')], max_length=20)),
            ],
        ),
    ]
