# Generated by Django 4.1.1 on 2022-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_l_alter_article_e_alter_article_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='D',
            field=models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08')], max_length=2),
        ),
    ]
