# Generated by Django 4.1.1 on 2022-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='E',
            field=models.CharField(choices=[('4', '4'), ('8', '8'), ('12', '12'), ('16', '16'), ('32', '32')], max_length=2),
        ),
    ]
