# Generated by Django 4.1.1 on 2022-09-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='L',
            field=models.CharField(choices=[('11', 'AC Fail Window')], max_length=20),
        ),
    ]
