# Generated by Django 4.1.1 on 2022-09-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='F',
            field=models.CharField(choices=[('X', 'X - Big'), ('Y', 'Y - Small'), ('Z', 'Z - Small & Big')], max_length=2),
        ),
    ]
