# Generated by Django 4.1.1 on 2022-09-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='L',
        ),
        migrations.AddField(
            model_name='article',
            name='M',
            field=models.CharField(choices=[('11', 'AC Fail Window')], default=11, max_length=20),
        ),
    ]
